name: acb
description: Aplicación para comandar el robot AgroCableBot.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^4.1.0+1
  mqtt_client: ^10.1.0
  sqflite: ^2.2.8+4
  http: ^0.13.6
  fl_chart: ^0.66.2
  flutter_mjpeg: ^2.0.4
  omni_datetime_picker: ^1.0.8
  flutter_logs: ^2.1.10
  path_provider: ^2.1.0
  permission_handler: ^11.3.0
  path: ^1.8.3
  intl: ^0.19.0
  simple_shadow: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  baseflow_plugin_template: ^2.1.2
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/plantas/
    - assets/appainter_theme.json

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21